version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/geo
    depends_on:
      - db
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: geodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: